import 'package:flutter/material.dart';

class CategoryIconOption {
  const CategoryIconOption(this.key, this.icon);

  final String key;
  final IconData icon;

  String get label => _labelFromKey(key);
}

const categoryIconOptions = [
  CategoryIconOption('wallet', Icons.account_balance_wallet_outlined),
  CategoryIconOption('utensils', Icons.restaurant),
  CategoryIconOption('car', Icons.directions_car_outlined),
  CategoryIconOption('receipt', Icons.receipt_long_outlined),
  CategoryIconOption('bag', Icons.shopping_bag_outlined),
  CategoryIconOption('heart', Icons.favorite_border),
  CategoryIconOption('piggy-bank', Icons.savings_outlined),
  CategoryIconOption('briefcase', Icons.work_outline),
  CategoryIconOption('home', Icons.home_outlined),
  CategoryIconOption('school', Icons.school_outlined),
  CategoryIconOption('flight', Icons.flight_takeoff_outlined),
  CategoryIconOption('gift', Icons.card_giftcard_outlined),
  CategoryIconOption('coffee', Icons.coffee_outlined),
  CategoryIconOption('phone', Icons.phone_iphone_outlined),
  CategoryIconOption('fitness', Icons.fitness_center_outlined),
  CategoryIconOption('shapes', Icons.category_outlined),
  CategoryIconOption('abc', Icons.abc),
  CategoryIconOption('ac_unit', Icons.ac_unit),
  CategoryIconOption('access_alarm', Icons.access_alarm),
  CategoryIconOption('access_alarms', Icons.access_alarms),
  CategoryIconOption('access_time', Icons.access_time),
  CategoryIconOption('access_time_filled', Icons.access_time_filled),
  CategoryIconOption('accessibility', Icons.accessibility),
  CategoryIconOption('accessibility_new', Icons.accessibility_new),
  CategoryIconOption('accessible', Icons.accessible),
  CategoryIconOption('accessible_forward', Icons.accessible_forward),
  CategoryIconOption('account_balance', Icons.account_balance),
  CategoryIconOption('account_balance_wallet', Icons.account_balance_wallet),
  CategoryIconOption('account_box', Icons.account_box),
  CategoryIconOption('account_circle', Icons.account_circle),
  CategoryIconOption('account_tree', Icons.account_tree),
  CategoryIconOption('ad_units', Icons.ad_units),
  CategoryIconOption('adb', Icons.adb),
  CategoryIconOption('add', Icons.add),
  CategoryIconOption('add_a_photo', Icons.add_a_photo),
  CategoryIconOption('add_alarm', Icons.add_alarm),
  CategoryIconOption('add_alert', Icons.add_alert),
  CategoryIconOption('add_box', Icons.add_box),
  CategoryIconOption('add_business', Icons.add_business),
  CategoryIconOption('add_call', Icons.add_call),
  CategoryIconOption('add_card', Icons.add_card),
  CategoryIconOption('add_chart', Icons.add_chart),
  CategoryIconOption('add_circle', Icons.add_circle),
  CategoryIconOption('add_circle_outline', Icons.add_circle_outline),
  CategoryIconOption('add_comment', Icons.add_comment),
  CategoryIconOption('add_home', Icons.add_home),
  CategoryIconOption('add_home_work', Icons.add_home_work),
  CategoryIconOption('add_ic_call', Icons.add_ic_call),
  CategoryIconOption('add_link', Icons.add_link),
  CategoryIconOption('add_location', Icons.add_location),
  CategoryIconOption('add_location_alt', Icons.add_location_alt),
  CategoryIconOption('add_moderator', Icons.add_moderator),
  CategoryIconOption('add_photo_alternate', Icons.add_photo_alternate),
  CategoryIconOption('add_reaction', Icons.add_reaction),
  CategoryIconOption('add_road', Icons.add_road),
  CategoryIconOption('add_shopping_cart', Icons.add_shopping_cart),
  CategoryIconOption('add_task', Icons.add_task),
  CategoryIconOption('add_to_drive', Icons.add_to_drive),
  CategoryIconOption('add_to_home_screen', Icons.add_to_home_screen),
  CategoryIconOption('add_to_photos', Icons.add_to_photos),
  CategoryIconOption('add_to_queue', Icons.add_to_queue),
  CategoryIconOption('addchart', Icons.addchart),
  CategoryIconOption('adf_scanner', Icons.adf_scanner),
  CategoryIconOption('adjust', Icons.adjust),
  CategoryIconOption('admin_panel_settings', Icons.admin_panel_settings),
  CategoryIconOption('adobe', Icons.adobe),
  CategoryIconOption('ads_click', Icons.ads_click),
  CategoryIconOption('agriculture', Icons.agriculture),
  CategoryIconOption('air', Icons.air),
  CategoryIconOption('airline_seat_flat', Icons.airline_seat_flat),
  CategoryIconOption(
    'airline_seat_flat_angled',
    Icons.airline_seat_flat_angled,
  ),
  CategoryIconOption(
    'airline_seat_individual_suite',
    Icons.airline_seat_individual_suite,
  ),
  CategoryIconOption(
    'airline_seat_legroom_extra',
    Icons.airline_seat_legroom_extra,
  ),
  CategoryIconOption(
    'airline_seat_legroom_normal',
    Icons.airline_seat_legroom_normal,
  ),
  CategoryIconOption(
    'airline_seat_legroom_reduced',
    Icons.airline_seat_legroom_reduced,
  ),
  CategoryIconOption(
    'airline_seat_recline_extra',
    Icons.airline_seat_recline_extra,
  ),
  CategoryIconOption(
    'airline_seat_recline_normal',
    Icons.airline_seat_recline_normal,
  ),
  CategoryIconOption('airline_stops', Icons.airline_stops),
  CategoryIconOption('airlines', Icons.airlines),
  CategoryIconOption('airplane_ticket', Icons.airplane_ticket),
  CategoryIconOption('airplanemode_active', Icons.airplanemode_active),
  CategoryIconOption('airplanemode_inactive', Icons.airplanemode_inactive),
  CategoryIconOption('airplanemode_off', Icons.airplanemode_off),
  CategoryIconOption('airplanemode_on', Icons.airplanemode_on),
  CategoryIconOption('airplay', Icons.airplay),
  CategoryIconOption('airport_shuttle', Icons.airport_shuttle),
  CategoryIconOption('alarm', Icons.alarm),
  CategoryIconOption('alarm_add', Icons.alarm_add),
  CategoryIconOption('alarm_off', Icons.alarm_off),
  CategoryIconOption('alarm_on', Icons.alarm_on),
  CategoryIconOption('album', Icons.album),
  CategoryIconOption('align_horizontal_center', Icons.align_horizontal_center),
  CategoryIconOption('align_horizontal_left', Icons.align_horizontal_left),
  CategoryIconOption('align_horizontal_right', Icons.align_horizontal_right),
  CategoryIconOption('align_vertical_bottom', Icons.align_vertical_bottom),
  CategoryIconOption('align_vertical_center', Icons.align_vertical_center),
  CategoryIconOption('align_vertical_top', Icons.align_vertical_top),
  CategoryIconOption('all_inbox', Icons.all_inbox),
  CategoryIconOption('all_inclusive', Icons.all_inclusive),
  CategoryIconOption('all_out', Icons.all_out),
  CategoryIconOption('alt_route', Icons.alt_route),
  CategoryIconOption('alternate_email', Icons.alternate_email),
  CategoryIconOption('amp_stories', Icons.amp_stories),
  CategoryIconOption('analytics', Icons.analytics),
  CategoryIconOption('anchor', Icons.anchor),
  CategoryIconOption('android', Icons.android),
  CategoryIconOption('animation', Icons.animation),
  CategoryIconOption('announcement', Icons.announcement),
  CategoryIconOption('aod', Icons.aod),
  CategoryIconOption('apartment', Icons.apartment),
  CategoryIconOption('api', Icons.api),
  CategoryIconOption('app_blocking', Icons.app_blocking),
  CategoryIconOption('app_registration', Icons.app_registration),
  CategoryIconOption('app_settings_alt', Icons.app_settings_alt),
  CategoryIconOption('app_shortcut', Icons.app_shortcut),
  CategoryIconOption('apple', Icons.apple),
  CategoryIconOption('approval', Icons.approval),
  CategoryIconOption('apps', Icons.apps),
  CategoryIconOption('apps_outage', Icons.apps_outage),
  CategoryIconOption('architecture', Icons.architecture),
  CategoryIconOption('archive', Icons.archive),
  CategoryIconOption('area_chart', Icons.area_chart),
  CategoryIconOption('arrow_back', Icons.arrow_back),
  CategoryIconOption('arrow_back_ios', Icons.arrow_back_ios),
  CategoryIconOption('arrow_back_ios_new', Icons.arrow_back_ios_new),
  CategoryIconOption('arrow_circle_down', Icons.arrow_circle_down),
  CategoryIconOption('arrow_circle_left', Icons.arrow_circle_left),
  CategoryIconOption('arrow_circle_right', Icons.arrow_circle_right),
  CategoryIconOption('arrow_circle_up', Icons.arrow_circle_up),
  CategoryIconOption('arrow_downward', Icons.arrow_downward),
  CategoryIconOption('arrow_drop_down', Icons.arrow_drop_down),
  CategoryIconOption('arrow_drop_down_circle', Icons.arrow_drop_down_circle),
  CategoryIconOption('arrow_drop_up', Icons.arrow_drop_up),
  CategoryIconOption('arrow_forward', Icons.arrow_forward),
  CategoryIconOption('arrow_forward_ios', Icons.arrow_forward_ios),
  CategoryIconOption('arrow_left', Icons.arrow_left),
  CategoryIconOption('arrow_outward', Icons.arrow_outward),
  CategoryIconOption('arrow_right', Icons.arrow_right),
  CategoryIconOption('arrow_right_alt', Icons.arrow_right_alt),
  CategoryIconOption('arrow_upward', Icons.arrow_upward),
  CategoryIconOption('art_track', Icons.art_track),
  CategoryIconOption('article', Icons.article),
  CategoryIconOption('aspect_ratio', Icons.aspect_ratio),
  CategoryIconOption('assessment', Icons.assessment),
  CategoryIconOption('assignment', Icons.assignment),
  CategoryIconOption('assignment_add', Icons.assignment_add),
  CategoryIconOption('assignment_ind', Icons.assignment_ind),
  CategoryIconOption('assignment_late', Icons.assignment_late),
  CategoryIconOption('assignment_return', Icons.assignment_return),
  CategoryIconOption('assignment_returned', Icons.assignment_returned),
  CategoryIconOption('assignment_turned_in', Icons.assignment_turned_in),
  CategoryIconOption('assist_walker', Icons.assist_walker),
  CategoryIconOption('assistant', Icons.assistant),
  CategoryIconOption('assistant_direction', Icons.assistant_direction),
  CategoryIconOption('assistant_navigation', Icons.assistant_navigation),
  CategoryIconOption('assistant_photo', Icons.assistant_photo),
  CategoryIconOption('assured_workload', Icons.assured_workload),
  CategoryIconOption('atm', Icons.atm),
  CategoryIconOption('attach_email', Icons.attach_email),
  CategoryIconOption('attach_file', Icons.attach_file),
  CategoryIconOption('attach_money', Icons.attach_money),
  CategoryIconOption('attachment', Icons.attachment),
  CategoryIconOption('attractions', Icons.attractions),
  CategoryIconOption('attribution', Icons.attribution),
  CategoryIconOption('audio_file', Icons.audio_file),
  CategoryIconOption('audiotrack', Icons.audiotrack),
  CategoryIconOption('auto_awesome', Icons.auto_awesome),
  CategoryIconOption('auto_awesome_mosaic', Icons.auto_awesome_mosaic),
  CategoryIconOption('auto_awesome_motion', Icons.auto_awesome_motion),
  CategoryIconOption('auto_delete', Icons.auto_delete),
  CategoryIconOption('auto_fix_high', Icons.auto_fix_high),
  CategoryIconOption('auto_fix_normal', Icons.auto_fix_normal),
  CategoryIconOption('auto_fix_off', Icons.auto_fix_off),
  CategoryIconOption('auto_graph', Icons.auto_graph),
  CategoryIconOption('auto_mode', Icons.auto_mode),
  CategoryIconOption('auto_stories', Icons.auto_stories),
  CategoryIconOption('autofps_select', Icons.autofps_select),
  CategoryIconOption('autorenew', Icons.autorenew),
  CategoryIconOption('av_timer', Icons.av_timer),
  CategoryIconOption('baby_changing_station', Icons.baby_changing_station),
  CategoryIconOption('back_hand', Icons.back_hand),
  CategoryIconOption('backpack', Icons.backpack),
  CategoryIconOption('backspace', Icons.backspace),
  CategoryIconOption('backup', Icons.backup),
  CategoryIconOption('backup_table', Icons.backup_table),
  CategoryIconOption('badge', Icons.badge),
  CategoryIconOption('bakery_dining', Icons.bakery_dining),
  CategoryIconOption('balance', Icons.balance),
  CategoryIconOption('balcony', Icons.balcony),
  CategoryIconOption('ballot', Icons.ballot),
  CategoryIconOption('bar_chart', Icons.bar_chart),
  CategoryIconOption('barcode_reader', Icons.barcode_reader),
  CategoryIconOption('batch_prediction', Icons.batch_prediction),
  CategoryIconOption('bathroom', Icons.bathroom),
  CategoryIconOption('bathtub', Icons.bathtub),
  CategoryIconOption('battery_0_bar', Icons.battery_0_bar),
  CategoryIconOption('battery_1_bar', Icons.battery_1_bar),
  CategoryIconOption('battery_2_bar', Icons.battery_2_bar),
  CategoryIconOption('battery_3_bar', Icons.battery_3_bar),
  CategoryIconOption('battery_4_bar', Icons.battery_4_bar),
  CategoryIconOption('battery_5_bar', Icons.battery_5_bar),
  CategoryIconOption('battery_6_bar', Icons.battery_6_bar),
  CategoryIconOption('battery_alert', Icons.battery_alert),
  CategoryIconOption('battery_charging_full', Icons.battery_charging_full),
  CategoryIconOption('battery_full', Icons.battery_full),
  CategoryIconOption('battery_saver', Icons.battery_saver),
  CategoryIconOption('battery_std', Icons.battery_std),
  CategoryIconOption('battery_unknown', Icons.battery_unknown),
  CategoryIconOption('beach_access', Icons.beach_access),
  CategoryIconOption('bed', Icons.bed),
  CategoryIconOption('bedroom_baby', Icons.bedroom_baby),
  CategoryIconOption('bedroom_child', Icons.bedroom_child),
  CategoryIconOption('bedroom_parent', Icons.bedroom_parent),
  CategoryIconOption('bedtime', Icons.bedtime),
  CategoryIconOption('bedtime_off', Icons.bedtime_off),
  CategoryIconOption('beenhere', Icons.beenhere),
  CategoryIconOption('bento', Icons.bento),
  CategoryIconOption('bike_scooter', Icons.bike_scooter),
  CategoryIconOption('biotech', Icons.biotech),
  CategoryIconOption('blender', Icons.blender),
  CategoryIconOption('blind', Icons.blind),
  CategoryIconOption('blinds', Icons.blinds),
  CategoryIconOption('blinds_closed', Icons.blinds_closed),
  CategoryIconOption('block', Icons.block),
  CategoryIconOption('block_flipped', Icons.block_flipped),
  CategoryIconOption('bloodtype', Icons.bloodtype),
  CategoryIconOption('bluetooth', Icons.bluetooth),
  CategoryIconOption('bluetooth_audio', Icons.bluetooth_audio),
  CategoryIconOption('bluetooth_connected', Icons.bluetooth_connected),
  CategoryIconOption('bluetooth_disabled', Icons.bluetooth_disabled),
  CategoryIconOption('bluetooth_drive', Icons.bluetooth_drive),
  CategoryIconOption('bluetooth_searching', Icons.bluetooth_searching),
  CategoryIconOption('blur_circular', Icons.blur_circular),
  CategoryIconOption('blur_linear', Icons.blur_linear),
  CategoryIconOption('blur_off', Icons.blur_off),
  CategoryIconOption('blur_on', Icons.blur_on),
  CategoryIconOption('bolt', Icons.bolt),
  CategoryIconOption('book', Icons.book),
  CategoryIconOption('book_online', Icons.book_online),
  CategoryIconOption('bookmark', Icons.bookmark),
  CategoryIconOption('bookmark_add', Icons.bookmark_add),
  CategoryIconOption('bookmark_added', Icons.bookmark_added),
  CategoryIconOption('bookmark_border', Icons.bookmark_border),
  CategoryIconOption('bookmark_outline', Icons.bookmark_outline),
  CategoryIconOption('bookmark_remove', Icons.bookmark_remove),
  CategoryIconOption('bookmarks', Icons.bookmarks),
  CategoryIconOption('border_all', Icons.border_all),
  CategoryIconOption('border_bottom', Icons.border_bottom),
  CategoryIconOption('border_clear', Icons.border_clear),
  CategoryIconOption('border_color', Icons.border_color),
  CategoryIconOption('border_horizontal', Icons.border_horizontal),
  CategoryIconOption('border_inner', Icons.border_inner),
  CategoryIconOption('border_left', Icons.border_left),
  CategoryIconOption('border_outer', Icons.border_outer),
  CategoryIconOption('border_right', Icons.border_right),
  CategoryIconOption('border_style', Icons.border_style),
  CategoryIconOption('border_top', Icons.border_top),
  CategoryIconOption('border_vertical', Icons.border_vertical),
  CategoryIconOption('boy', Icons.boy),
  CategoryIconOption('branding_watermark', Icons.branding_watermark),
  CategoryIconOption('breakfast_dining', Icons.breakfast_dining),
  CategoryIconOption('brightness_1', Icons.brightness_1),
  CategoryIconOption('brightness_2', Icons.brightness_2),
  CategoryIconOption('brightness_3', Icons.brightness_3),
  CategoryIconOption('brightness_4', Icons.brightness_4),
  CategoryIconOption('brightness_5', Icons.brightness_5),
  CategoryIconOption('brightness_6', Icons.brightness_6),
  CategoryIconOption('brightness_7', Icons.brightness_7),
  CategoryIconOption('brightness_auto', Icons.brightness_auto),
  CategoryIconOption('brightness_high', Icons.brightness_high),
  CategoryIconOption('brightness_low', Icons.brightness_low),
  CategoryIconOption('brightness_medium', Icons.brightness_medium),
  CategoryIconOption('broadcast_on_home', Icons.broadcast_on_home),
  CategoryIconOption('broadcast_on_personal', Icons.broadcast_on_personal),
  CategoryIconOption('broken_image', Icons.broken_image),
  CategoryIconOption('browse_gallery', Icons.browse_gallery),
  CategoryIconOption('browser_not_supported', Icons.browser_not_supported),
  CategoryIconOption('browser_updated', Icons.browser_updated),
  CategoryIconOption('brunch_dining', Icons.brunch_dining),
  CategoryIconOption('brush', Icons.brush),
  CategoryIconOption('bubble_chart', Icons.bubble_chart),
  CategoryIconOption('bug_report', Icons.bug_report),
  CategoryIconOption('build', Icons.build),
  CategoryIconOption('build_circle', Icons.build_circle),
  CategoryIconOption('bungalow', Icons.bungalow),
  CategoryIconOption('burst_mode', Icons.burst_mode),
  CategoryIconOption('bus_alert', Icons.bus_alert),
  CategoryIconOption('business', Icons.business),
  CategoryIconOption('business_center', Icons.business_center),
  CategoryIconOption('cabin', Icons.cabin),
  CategoryIconOption('cable', Icons.cable),
  CategoryIconOption('cached', Icons.cached),
  CategoryIconOption('cake', Icons.cake),
  CategoryIconOption('calculate', Icons.calculate),
  CategoryIconOption('calendar_month', Icons.calendar_month),
  CategoryIconOption('calendar_today', Icons.calendar_today),
  CategoryIconOption('calendar_view_day', Icons.calendar_view_day),
  CategoryIconOption('calendar_view_month', Icons.calendar_view_month),
  CategoryIconOption('calendar_view_week', Icons.calendar_view_week),
  CategoryIconOption('call', Icons.call),
  CategoryIconOption('call_end', Icons.call_end),
  CategoryIconOption('call_made', Icons.call_made),
  CategoryIconOption('call_merge', Icons.call_merge),
  CategoryIconOption('call_missed', Icons.call_missed),
  CategoryIconOption('call_missed_outgoing', Icons.call_missed_outgoing),
  CategoryIconOption('call_received', Icons.call_received),
  CategoryIconOption('call_split', Icons.call_split),
  CategoryIconOption('call_to_action', Icons.call_to_action),
  CategoryIconOption('camera', Icons.camera),
  CategoryIconOption('camera_alt', Icons.camera_alt),
  CategoryIconOption('camera_enhance', Icons.camera_enhance),
  CategoryIconOption('camera_front', Icons.camera_front),
  CategoryIconOption('camera_indoor', Icons.camera_indoor),
  CategoryIconOption('camera_outdoor', Icons.camera_outdoor),
  CategoryIconOption('camera_rear', Icons.camera_rear),
  CategoryIconOption('camera_roll', Icons.camera_roll),
];

IconData iconFor(String? key) {
  for (final option in categoryIconOptions) {
    if (option.key == key) return option.icon;
  }
  return Icons.category_outlined;
}

String categoryIconLabel(String key) {
  for (final option in categoryIconOptions) {
    if (option.key == key) return option.label;
  }
  return 'Other';
}

String _labelFromKey(String key) {
  return key
      .replaceAll('-', ' ')
      .replaceAll('_', ' ')
      .split(' ')
      .where((part) => part.isNotEmpty)
      .map((part) => part[0].toUpperCase() + part.substring(1))
      .join(' ');
}
